### ISSUE TITLE
 where is the code

### ISSUE THREAD

**Issue by laoshuai** [simonech/TriathlonRaceTracking#2]
I got the book.But, where is the code?

**Comment by simonech** [comment]
Hi, code for the book is available on Wrox website:
http://www.wrox.com/WileyCDA/WroxTitle/Front-end-Development-with-ASP-NET-Core-Angular-and-Bootstrap.productCd-1119181313,descCd-DOWNLOAD.html

The complete sample for the last chapter is not available yet
